on: push
name: Build Angular
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.3.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}
      - run: yarn install

      - run: yarn test

#      - name: Push Build to Releases
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "dist/angular-githubaction/*"
#          token: ${{ secrets.TOKEN }}
