name: Build
on:
    push:
        branches: 
            master
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}    
    
jobs:
#  test:
#    runs-on: ubuntu-latest
    
#    steps:
#      - name: Git Clone
#        uses: actions/checkout@v2
#      - name: Use Node.js 14.x
#        uses: actions/setup-node@v2
#        with:
#          node-version: 14.x

#      - name: Setup
#        run: npm i

#      - name: Test
#        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
    
 build:
    runs-on: ubuntu-latest
#    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Setup
        run: npm i
      - name: Build
        run: npm run build
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist 

 deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: dist 
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}{% raw %}      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true    
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
