name: Build
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git Clone
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup
        run: npm i

      - name: Test
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
    
  build:
      runs-on: ubuntu-latest
      needs: [test]
      steps:
      - name: Git Clone
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup
        run: npm i
      - name: build
        run: npm build
    
